t2/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('t2app.urls')),
]

t2app/urls.py
from django.urls import path
from t2app import views

urlpatterns = [
    # path('filter/', views.filter_boxes, name='filter_boxes'),
    # path('about',views.about),
    # path('abt',views.abt),
    path('all', views.all), 
    path('catfilter/<cv>',views.catfilter), 
    path('locfilter/<vc>',views.locfilter),
    path('search',views.search),
]

t2app/models.py
from django.db import models

# Create your models here.

class course(models.Model):
    CAT=((1,'spritual'),(2,'Historical'),(3,'adventure'))
    loc=((1,'Rajasthan'),(2,'Delhi'),(3,'Gujrat'),(4,'Maharastra'))
    name=models.CharField(max_length=100 ,verbose_name='place Name')
    cat=models.IntegerField(verbose_name='Category' ,choices=CAT)
    lc=models.IntegerField(verbose_name='locations' ,choices=loc)
    cdetail=models.CharField(max_length=300, verbose_name='place Detail')
    cimage=models.ImageField(upload_to='image')
    is_active=models.BooleanField(default=True)

t2app/views.py
from django.shortcuts import render
from t2app.models import course
from django.db.models import Q
# from .models import Box

# def filter_boxes(request):
#     location_filter = request.GET.get('location', 'all_locations')
    
#     if location_filter == 'all_locations':
#         boxes = Box.objects.all()
#     else:
#         boxes = Box.objects.filter(location=location_filter)

#     return render(request, 'index.htm


def search(request):
    context={}
    query=request.GET['query']
    #print(query)
    pname=course.objects.filter(name__icontains=query)
    pdetail=course.objects.filter(cdetail__icontains=query)
    pcat=course.objects.filter(cat__icontains=query)
    allproducts=pname.union(pdetail,pcat)
    if allproducts.count()==0:
        context['errmsg']='Products Not Found'
    context['data']=allproducts
    return render(request,'base.html',context)

def all(request):
    p=course.objects.filter(is_active=True)
    context={}
    context['data']=p
    return render(request,'base.html',context)

def catfilter(request,cv):
    print(cv)
    q1=Q(cat=cv)
    q2=Q(is_active=True)

    p=course.objects.filter(q1 & q2)

    context={}
    context['data']=p
    return render(request,'base.html',context)

def locfilter(request,vc):
    print(vc)
    q1=Q(lc=vc)
    q2=Q(is_active=True)

    p=course.objects.filter(q1 & q2)

    context={}
    context['data']=p
    return render(request,'base.html',context)

t2app/templates/base.html
{% include 'header.html' %}
{% block 'main' %}
{% load static %}
<!-- Menu Start -->
<div class="container-fluid py-5">
    <div class="container">
        <div class="my-5">
            <form class="form-inline my-2 my-lg-0" action="/search">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="query" style="border-radius: 20px;">
                <button class="btn btn-dark my-2 my-sm-0" style="border-radius: 20px;" type="submit">Search</button>
            </form>
        </div>
        
        <div class="row">
            {% for x in data %}

            <div class="col-lg-4 col-md-6 mb-4">
                <div class="rounded overflow-hidden mb-2">
                    <!-- <img class="img-fluid" src="{{ x.cimage.url}}" alt="..." style="aspect-ratio: 10/7;"> -->
                    <div class=" p-4" style="background-color: black; color: white;">
                                                <a class="h5" href="">{{x.name}},</a>
                                                <a class="h5" href="">{{ x.get_lc_display }}</a>
                                                <p>{{ x.get_cat_display }}</p>
                                                <!-- <a class="h5" href="" style="color: red;"></a> -->
                        <div class="border-top mt-4 pt-4">
                            <div class="d-flex justify-content-between">
                                
                                
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}

            
        </div>
    </div>
</div>
<!-- Menu End -->
{% endblock 'main' %}
{% include 'footer.html' %}

t2app/templates/footer.html
{% load static %}

<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/popper.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
   <script src="{% static 'vendor/bootstrap/popper.min.js' %}"></script>
   <script src="{% static 'vendor/bootstrap/bootstrap.min.js' %}"></script>
   <script src="{% static 'vendor/select2/select2.min.js' %}"></script>
   <script src="{% static 'vendor/owlcarousel/owl.carousel.min.js' %}"></script>
   <script src="https://cdn.rawgit.com/noelboss/featherlight/1.7.13/release/featherlight.min.js"></script>
   <script src="{% static 'vendor/stellar/jquery.stellar.js' %}" type="text/javascript" charset="utf-8"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/js/tempusdominus-bootstrap-4.min.js"></script>

   <!-- Main JS -->
   <script src="{% static 'js/app.min.js ' %}"></script>
</body>

t2app/templates/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>task2</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/select2/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/owlcarousel/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="https://cdn.rawgit.com/noelboss/featherlight/1.7.13/release/featherlight.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/css/tempusdominus-bootstrap-4.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.1/css/brands.css">

</head>
<body class="bg-secondary">
    <div>
        <div class="row"><!--header section start-->
            <div class="col-md-3 mt-3">
                <nav class="navbar navbar-expand-lg navbar-dark bg-dark text-white">
                    <div class="container-fluid">
                      
                          <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              Explore category
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                              <a class="dropdown-item" href="/catfilter/1">Spritual</a>
                              <a class="dropdown-item" href="/catfilter/2">Historical</a>
                              <a class="dropdown-item" href="/catfilter/3">Adventure</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Explore locaions
                          </a>
                          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="/locfilter/1">Rajasthan</a>
                            <a class="dropdown-item" href="/locfilter/2">Delhi</a>
                            <a class="dropdown-item" href="/locfilter/3">Gujrat</a>
                            <a class="dropdown-item" href="/locfilter/4">Maharastra</a>
                          </div>
                      </li>
                          
                        </ul>
                      </div>
                    </div>
                  </nav>
            </div>
        </div><!--header sectioin end-->

t2app/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block 'main' %}
<div class="container p-5">
    <div class="row mb-4 mx-auto ">
      <div class="col-md-3 bg-secondary shadow p-3 anchor  ">
        <a href="/account_master">ACCOUNT MANAGER ADD</a>
      </div>
      <div class="col-md-3 bg-secondary shadow p-3 anchor offset-1">
        <a href="/sale">SALES INVOICE ADD</a>
      </div>
      <div class="col-md-3 bg-secondary shadow p-3 anchor offset-1">
        <a href="">ACCOUNT LEDGER</a>
      </div>
    </div>
    <div class="row mb-4 mx-auto">
      <div class="col-md-3 bg-secondary shadow p-3 anchor ">
        <a href="/account_list">ACCOUNT MANAGER DISPLAY</a>
      </div>
      <div class="col-md-3 bg-secondary shadow p-3 anchor offset-1 ">
        <a href="/sale_list">SALES INVOICE DISPLAY</a>
      </div>
      <div class="col-md-3 bg-secondary shadow p-3 anchor offset-1 ">
        <a href="">PRODUCT LEDGER</a>
      </div>
    </div>
    <div class="row mb-4 mx-auto">
      <div class="col-md-3 bg-secondary shadow p-3 anchor  ">
        <a href="/product_master">PRODUCT MASTER ADD</a>
      </div>
      <div class="col-md-3 bg-secondary shadow p-3 anchor offset-1 ">
        <a href="">PURCHASE INVOIVE ADD</a>
      </div>
      <div class="col-md-3 bg-secondary shadow p-3 anchor offset-1 ">
        <a href="">OUTSTANDING RECEIVABLE</a>
      </div>
    </div>
    <div class="row mb-4 mx-auto">
      <div class="col-md-3 bg-secondary shadow p-3 anchor  ">
        <a href="/product_list">PRODUCT MASTER DISPLAY</a>
      </div>
      <div class="col-md-3 bg-secondary shadow p-3 anchor offset-1 ">
        <a href="">PURCHASE INVOIVE DISPLAY</a>
      </div>
      <div class="col-md-3 bg-secondary shadow p-3 anchor offset-1 ">
        <a href="sales list.html">SALES REGISTER</a>
      </div>
    </div>
    <div class="row mb-4 mx-auto">
      <div class="col-md-3 bg-secondary shadow p-3 anchor  ">
        <a href="">REMINDER</a>
      </div>
      <div class="col-md-3 bg-secondary shadow p-3 anchor offset-1 ">
        <a href="">QUICK ENTRY</a>
      </div>
      <div class="col-md-3 bg-secondary shadow p-3 anchor offset-1 ">
        <a href="">GST REPORTS</a>
      </div>
    </div>
    
  </div>
  {% endblock 'main' %}